require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CollaboratorRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # CollaboratorRequest. As you add validations to CollaboratorRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "exercise_collaborator_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CollaboratorRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all collaborator_requests as @collaborator_requests" do
      collaborator_request = CollaboratorRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:collaborator_requests).should eq([collaborator_request])
    end
  end

  describe "GET show" do
    it "assigns the requested collaborator_request as @collaborator_request" do
      collaborator_request = CollaboratorRequest.create! valid_attributes
      get :show, {:id => collaborator_request.to_param}, valid_session
      assigns(:collaborator_request).should eq(collaborator_request)
    end
  end

  describe "GET new" do
    it "assigns a new collaborator_request as @collaborator_request" do
      get :new, {}, valid_session
      assigns(:collaborator_request).should be_a_new(CollaboratorRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested collaborator_request as @collaborator_request" do
      collaborator_request = CollaboratorRequest.create! valid_attributes
      get :edit, {:id => collaborator_request.to_param}, valid_session
      assigns(:collaborator_request).should eq(collaborator_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CollaboratorRequest" do
        expect {
          post :create, {:collaborator_request => valid_attributes}, valid_session
        }.to change(CollaboratorRequest, :count).by(1)
      end

      it "assigns a newly created collaborator_request as @collaborator_request" do
        post :create, {:collaborator_request => valid_attributes}, valid_session
        assigns(:collaborator_request).should be_a(CollaboratorRequest)
        assigns(:collaborator_request).should be_persisted
      end

      it "redirects to the created collaborator_request" do
        post :create, {:collaborator_request => valid_attributes}, valid_session
        response.should redirect_to(CollaboratorRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved collaborator_request as @collaborator_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollaboratorRequest.any_instance.stub(:save).and_return(false)
        post :create, {:collaborator_request => { "exercise_collaborator_id" => "invalid value" }}, valid_session
        assigns(:collaborator_request).should be_a_new(CollaboratorRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CollaboratorRequest.any_instance.stub(:save).and_return(false)
        post :create, {:collaborator_request => { "exercise_collaborator_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested collaborator_request" do
        collaborator_request = CollaboratorRequest.create! valid_attributes
        # Assuming there are no other collaborator_requests in the database, this
        # specifies that the CollaboratorRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CollaboratorRequest.any_instance.should_receive(:update_attributes).with({ "exercise_collaborator_id" => "1" })
        put :update, {:id => collaborator_request.to_param, :collaborator_request => { "exercise_collaborator_id" => "1" }}, valid_session
      end

      it "assigns the requested collaborator_request as @collaborator_request" do
        collaborator_request = CollaboratorRequest.create! valid_attributes
        put :update, {:id => collaborator_request.to_param, :collaborator_request => valid_attributes}, valid_session
        assigns(:collaborator_request).should eq(collaborator_request)
      end

      it "redirects to the collaborator_request" do
        collaborator_request = CollaboratorRequest.create! valid_attributes
        put :update, {:id => collaborator_request.to_param, :collaborator_request => valid_attributes}, valid_session
        response.should redirect_to(collaborator_request)
      end
    end

    describe "with invalid params" do
      it "assigns the collaborator_request as @collaborator_request" do
        collaborator_request = CollaboratorRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollaboratorRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => collaborator_request.to_param, :collaborator_request => { "exercise_collaborator_id" => "invalid value" }}, valid_session
        assigns(:collaborator_request).should eq(collaborator_request)
      end

      it "re-renders the 'edit' template" do
        collaborator_request = CollaboratorRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CollaboratorRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => collaborator_request.to_param, :collaborator_request => { "exercise_collaborator_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested collaborator_request" do
      collaborator_request = CollaboratorRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => collaborator_request.to_param}, valid_session
      }.to change(CollaboratorRequest, :count).by(-1)
    end

    it "redirects to the collaborator_requests list" do
      collaborator_request = CollaboratorRequest.create! valid_attributes
      delete :destroy, {:id => collaborator_request.to_param}, valid_session
      response.should redirect_to(collaborator_requests_url)
    end
  end

end
