require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseDerivationsController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseDerivation. As you add validations to ExerciseDerivation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "derived_exercise_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseDerivationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exercise_derivations as @exercise_derivations" do
      exercise_derivation = ExerciseDerivation.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_derivations).should eq([exercise_derivation])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_derivation as @exercise_derivation" do
      exercise_derivation = ExerciseDerivation.create! valid_attributes
      get :show, {:id => exercise_derivation.to_param}, valid_session
      assigns(:exercise_derivation).should eq(exercise_derivation)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_derivation as @exercise_derivation" do
      get :new, {}, valid_session
      assigns(:exercise_derivation).should be_a_new(ExerciseDerivation)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_derivation as @exercise_derivation" do
      exercise_derivation = ExerciseDerivation.create! valid_attributes
      get :edit, {:id => exercise_derivation.to_param}, valid_session
      assigns(:exercise_derivation).should eq(exercise_derivation)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseDerivation" do
        expect {
          post :create, {:exercise_derivation => valid_attributes}, valid_session
        }.to change(ExerciseDerivation, :count).by(1)
      end

      it "assigns a newly created exercise_derivation as @exercise_derivation" do
        post :create, {:exercise_derivation => valid_attributes}, valid_session
        assigns(:exercise_derivation).should be_a(ExerciseDerivation)
        assigns(:exercise_derivation).should be_persisted
      end

      it "redirects to the created exercise_derivation" do
        post :create, {:exercise_derivation => valid_attributes}, valid_session
        response.should redirect_to(ExerciseDerivation.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_derivation as @exercise_derivation" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseDerivation.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_derivation => { "derived_exercise_id" => "invalid value" }}, valid_session
        assigns(:exercise_derivation).should be_a_new(ExerciseDerivation)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseDerivation.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_derivation => { "derived_exercise_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_derivation" do
        exercise_derivation = ExerciseDerivation.create! valid_attributes
        # Assuming there are no other exercise_derivations in the database, this
        # specifies that the ExerciseDerivation created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseDerivation.any_instance.should_receive(:update_attributes).with({ "derived_exercise_id" => "1" })
        put :update, {:id => exercise_derivation.to_param, :exercise_derivation => { "derived_exercise_id" => "1" }}, valid_session
      end

      it "assigns the requested exercise_derivation as @exercise_derivation" do
        exercise_derivation = ExerciseDerivation.create! valid_attributes
        put :update, {:id => exercise_derivation.to_param, :exercise_derivation => valid_attributes}, valid_session
        assigns(:exercise_derivation).should eq(exercise_derivation)
      end

      it "redirects to the exercise_derivation" do
        exercise_derivation = ExerciseDerivation.create! valid_attributes
        put :update, {:id => exercise_derivation.to_param, :exercise_derivation => valid_attributes}, valid_session
        response.should redirect_to(exercise_derivation)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_derivation as @exercise_derivation" do
        exercise_derivation = ExerciseDerivation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseDerivation.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_derivation.to_param, :exercise_derivation => { "derived_exercise_id" => "invalid value" }}, valid_session
        assigns(:exercise_derivation).should eq(exercise_derivation)
      end

      it "re-renders the 'edit' template" do
        exercise_derivation = ExerciseDerivation.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseDerivation.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_derivation.to_param, :exercise_derivation => { "derived_exercise_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_derivation" do
      exercise_derivation = ExerciseDerivation.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_derivation.to_param}, valid_session
      }.to change(ExerciseDerivation, :count).by(-1)
    end

    it "redirects to the exercise_derivations list" do
      exercise_derivation = ExerciseDerivation.create! valid_attributes
      delete :destroy, {:id => exercise_derivation.to_param}, valid_session
      response.should redirect_to(exercise_derivations_url)
    end
  end

end
