require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExerciseCollaboratorsController do

  # This should return the minimal set of attributes required to create a valid
  # ExerciseCollaborator. As you add validations to ExerciseCollaborator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExerciseCollaboratorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exercise_collaborators as @exercise_collaborators" do
      exercise_collaborator = ExerciseCollaborator.create! valid_attributes
      get :index, {}, valid_session
      assigns(:exercise_collaborators).should eq([exercise_collaborator])
    end
  end

  describe "GET show" do
    it "assigns the requested exercise_collaborator as @exercise_collaborator" do
      exercise_collaborator = ExerciseCollaborator.create! valid_attributes
      get :show, {:id => exercise_collaborator.to_param}, valid_session
      assigns(:exercise_collaborator).should eq(exercise_collaborator)
    end
  end

  describe "GET new" do
    it "assigns a new exercise_collaborator as @exercise_collaborator" do
      get :new, {}, valid_session
      assigns(:exercise_collaborator).should be_a_new(ExerciseCollaborator)
    end
  end

  describe "GET edit" do
    it "assigns the requested exercise_collaborator as @exercise_collaborator" do
      exercise_collaborator = ExerciseCollaborator.create! valid_attributes
      get :edit, {:id => exercise_collaborator.to_param}, valid_session
      assigns(:exercise_collaborator).should eq(exercise_collaborator)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ExerciseCollaborator" do
        expect {
          post :create, {:exercise_collaborator => valid_attributes}, valid_session
        }.to change(ExerciseCollaborator, :count).by(1)
      end

      it "assigns a newly created exercise_collaborator as @exercise_collaborator" do
        post :create, {:exercise_collaborator => valid_attributes}, valid_session
        assigns(:exercise_collaborator).should be_a(ExerciseCollaborator)
        assigns(:exercise_collaborator).should be_persisted
      end

      it "redirects to the created exercise_collaborator" do
        post :create, {:exercise_collaborator => valid_attributes}, valid_session
        response.should redirect_to(ExerciseCollaborator.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exercise_collaborator as @exercise_collaborator" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCollaborator.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_collaborator => { "user_id" => "invalid value" }}, valid_session
        assigns(:exercise_collaborator).should be_a_new(ExerciseCollaborator)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCollaborator.any_instance.stub(:save).and_return(false)
        post :create, {:exercise_collaborator => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested exercise_collaborator" do
        exercise_collaborator = ExerciseCollaborator.create! valid_attributes
        # Assuming there are no other exercise_collaborators in the database, this
        # specifies that the ExerciseCollaborator created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ExerciseCollaborator.any_instance.should_receive(:update_attributes).with({ "user_id" => "1" })
        put :update, {:id => exercise_collaborator.to_param, :exercise_collaborator => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested exercise_collaborator as @exercise_collaborator" do
        exercise_collaborator = ExerciseCollaborator.create! valid_attributes
        put :update, {:id => exercise_collaborator.to_param, :exercise_collaborator => valid_attributes}, valid_session
        assigns(:exercise_collaborator).should eq(exercise_collaborator)
      end

      it "redirects to the exercise_collaborator" do
        exercise_collaborator = ExerciseCollaborator.create! valid_attributes
        put :update, {:id => exercise_collaborator.to_param, :exercise_collaborator => valid_attributes}, valid_session
        response.should redirect_to(exercise_collaborator)
      end
    end

    describe "with invalid params" do
      it "assigns the exercise_collaborator as @exercise_collaborator" do
        exercise_collaborator = ExerciseCollaborator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCollaborator.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_collaborator.to_param, :exercise_collaborator => { "user_id" => "invalid value" }}, valid_session
        assigns(:exercise_collaborator).should eq(exercise_collaborator)
      end

      it "re-renders the 'edit' template" do
        exercise_collaborator = ExerciseCollaborator.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ExerciseCollaborator.any_instance.stub(:save).and_return(false)
        put :update, {:id => exercise_collaborator.to_param, :exercise_collaborator => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exercise_collaborator" do
      exercise_collaborator = ExerciseCollaborator.create! valid_attributes
      expect {
        delete :destroy, {:id => exercise_collaborator.to_param}, valid_session
      }.to change(ExerciseCollaborator, :count).by(-1)
    end

    it "redirects to the exercise_collaborators list" do
      exercise_collaborator = ExerciseCollaborator.create! valid_attributes
      delete :destroy, {:id => exercise_collaborator.to_param}, valid_session
      response.should redirect_to(exercise_collaborators_url)
    end
  end

end
