require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FillInTheBlankAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # FillInTheBlankAnswer. As you add validations to FillInTheBlankAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FillInTheBlankAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all fill_in_the_blank_answers as @fill_in_the_blank_answers" do
      fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:fill_in_the_blank_answers).should eq([fill_in_the_blank_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested fill_in_the_blank_answer as @fill_in_the_blank_answer" do
      fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
      get :show, {:id => fill_in_the_blank_answer.to_param}, valid_session
      assigns(:fill_in_the_blank_answer).should eq(fill_in_the_blank_answer)
    end
  end

  describe "GET new" do
    it "assigns a new fill_in_the_blank_answer as @fill_in_the_blank_answer" do
      get :new, {}, valid_session
      assigns(:fill_in_the_blank_answer).should be_a_new(FillInTheBlankAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested fill_in_the_blank_answer as @fill_in_the_blank_answer" do
      fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
      get :edit, {:id => fill_in_the_blank_answer.to_param}, valid_session
      assigns(:fill_in_the_blank_answer).should eq(fill_in_the_blank_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FillInTheBlankAnswer" do
        expect {
          post :create, {:fill_in_the_blank_answer => valid_attributes}, valid_session
        }.to change(FillInTheBlankAnswer, :count).by(1)
      end

      it "assigns a newly created fill_in_the_blank_answer as @fill_in_the_blank_answer" do
        post :create, {:fill_in_the_blank_answer => valid_attributes}, valid_session
        assigns(:fill_in_the_blank_answer).should be_a(FillInTheBlankAnswer)
        assigns(:fill_in_the_blank_answer).should be_persisted
      end

      it "redirects to the created fill_in_the_blank_answer" do
        post :create, {:fill_in_the_blank_answer => valid_attributes}, valid_session
        response.should redirect_to(FillInTheBlankAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved fill_in_the_blank_answer as @fill_in_the_blank_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        FillInTheBlankAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:fill_in_the_blank_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:fill_in_the_blank_answer).should be_a_new(FillInTheBlankAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FillInTheBlankAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:fill_in_the_blank_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested fill_in_the_blank_answer" do
        fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
        # Assuming there are no other fill_in_the_blank_answers in the database, this
        # specifies that the FillInTheBlankAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FillInTheBlankAnswer.any_instance.should_receive(:update_attributes).with({ "question_id" => "1" })
        put :update, {:id => fill_in_the_blank_answer.to_param, :fill_in_the_blank_answer => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested fill_in_the_blank_answer as @fill_in_the_blank_answer" do
        fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
        put :update, {:id => fill_in_the_blank_answer.to_param, :fill_in_the_blank_answer => valid_attributes}, valid_session
        assigns(:fill_in_the_blank_answer).should eq(fill_in_the_blank_answer)
      end

      it "redirects to the fill_in_the_blank_answer" do
        fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
        put :update, {:id => fill_in_the_blank_answer.to_param, :fill_in_the_blank_answer => valid_attributes}, valid_session
        response.should redirect_to(fill_in_the_blank_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the fill_in_the_blank_answer as @fill_in_the_blank_answer" do
        fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FillInTheBlankAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => fill_in_the_blank_answer.to_param, :fill_in_the_blank_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:fill_in_the_blank_answer).should eq(fill_in_the_blank_answer)
      end

      it "re-renders the 'edit' template" do
        fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FillInTheBlankAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => fill_in_the_blank_answer.to_param, :fill_in_the_blank_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested fill_in_the_blank_answer" do
      fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => fill_in_the_blank_answer.to_param}, valid_session
      }.to change(FillInTheBlankAnswer, :count).by(-1)
    end

    it "redirects to the fill_in_the_blank_answers list" do
      fill_in_the_blank_answer = FillInTheBlankAnswer.create! valid_attributes
      delete :destroy, {:id => fill_in_the_blank_answer.to_param}, valid_session
      response.should redirect_to(fill_in_the_blank_answers_url)
    end
  end

end
