require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe FreeResponsesController do

  # This should return the minimal set of attributes required to create a valid
  # FreeResponse. As you add validations to FreeResponse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # FreeResponsesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all free_responses as @free_responses" do
      free_response = FreeResponse.create! valid_attributes
      get :index, {}, valid_session
      assigns(:free_responses).should eq([free_response])
    end
  end

  describe "GET show" do
    it "assigns the requested free_response as @free_response" do
      free_response = FreeResponse.create! valid_attributes
      get :show, {:id => free_response.to_param}, valid_session
      assigns(:free_response).should eq(free_response)
    end
  end

  describe "GET new" do
    it "assigns a new free_response as @free_response" do
      get :new, {}, valid_session
      assigns(:free_response).should be_a_new(FreeResponse)
    end
  end

  describe "GET edit" do
    it "assigns the requested free_response as @free_response" do
      free_response = FreeResponse.create! valid_attributes
      get :edit, {:id => free_response.to_param}, valid_session
      assigns(:free_response).should eq(free_response)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new FreeResponse" do
        expect {
          post :create, {:free_response => valid_attributes}, valid_session
        }.to change(FreeResponse, :count).by(1)
      end

      it "assigns a newly created free_response as @free_response" do
        post :create, {:free_response => valid_attributes}, valid_session
        assigns(:free_response).should be_a(FreeResponse)
        assigns(:free_response).should be_persisted
      end

      it "redirects to the created free_response" do
        post :create, {:free_response => valid_attributes}, valid_session
        response.should redirect_to(FreeResponse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved free_response as @free_response" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeResponse.any_instance.stub(:save).and_return(false)
        post :create, {:free_response => { "question_id" => "invalid value" }}, valid_session
        assigns(:free_response).should be_a_new(FreeResponse)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        FreeResponse.any_instance.stub(:save).and_return(false)
        post :create, {:free_response => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested free_response" do
        free_response = FreeResponse.create! valid_attributes
        # Assuming there are no other free_responses in the database, this
        # specifies that the FreeResponse created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        FreeResponse.any_instance.should_receive(:update_attributes).with({ "question_id" => "1" })
        put :update, {:id => free_response.to_param, :free_response => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested free_response as @free_response" do
        free_response = FreeResponse.create! valid_attributes
        put :update, {:id => free_response.to_param, :free_response => valid_attributes}, valid_session
        assigns(:free_response).should eq(free_response)
      end

      it "redirects to the free_response" do
        free_response = FreeResponse.create! valid_attributes
        put :update, {:id => free_response.to_param, :free_response => valid_attributes}, valid_session
        response.should redirect_to(free_response)
      end
    end

    describe "with invalid params" do
      it "assigns the free_response as @free_response" do
        free_response = FreeResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => free_response.to_param, :free_response => { "question_id" => "invalid value" }}, valid_session
        assigns(:free_response).should eq(free_response)
      end

      it "re-renders the 'edit' template" do
        free_response = FreeResponse.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        FreeResponse.any_instance.stub(:save).and_return(false)
        put :update, {:id => free_response.to_param, :free_response => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested free_response" do
      free_response = FreeResponse.create! valid_attributes
      expect {
        delete :destroy, {:id => free_response.to_param}, valid_session
      }.to change(FreeResponse, :count).by(-1)
    end

    it "redirects to the free_responses list" do
      free_response = FreeResponse.create! valid_attributes
      delete :destroy, {:id => free_response.to_param}, valid_session
      response.should redirect_to(free_responses_url)
    end
  end

end
