require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MatchingAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # MatchingAnswer. As you add validations to MatchingAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MatchingAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all matching_answers as @matching_answers" do
      matching_answer = MatchingAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:matching_answers).should eq([matching_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested matching_answer as @matching_answer" do
      matching_answer = MatchingAnswer.create! valid_attributes
      get :show, {:id => matching_answer.to_param}, valid_session
      assigns(:matching_answer).should eq(matching_answer)
    end
  end

  describe "GET new" do
    it "assigns a new matching_answer as @matching_answer" do
      get :new, {}, valid_session
      assigns(:matching_answer).should be_a_new(MatchingAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested matching_answer as @matching_answer" do
      matching_answer = MatchingAnswer.create! valid_attributes
      get :edit, {:id => matching_answer.to_param}, valid_session
      assigns(:matching_answer).should eq(matching_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MatchingAnswer" do
        expect {
          post :create, {:matching_answer => valid_attributes}, valid_session
        }.to change(MatchingAnswer, :count).by(1)
      end

      it "assigns a newly created matching_answer as @matching_answer" do
        post :create, {:matching_answer => valid_attributes}, valid_session
        assigns(:matching_answer).should be_a(MatchingAnswer)
        assigns(:matching_answer).should be_persisted
      end

      it "redirects to the created matching_answer" do
        post :create, {:matching_answer => valid_attributes}, valid_session
        response.should redirect_to(MatchingAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved matching_answer as @matching_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        MatchingAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:matching_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:matching_answer).should be_a_new(MatchingAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MatchingAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:matching_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested matching_answer" do
        matching_answer = MatchingAnswer.create! valid_attributes
        # Assuming there are no other matching_answers in the database, this
        # specifies that the MatchingAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MatchingAnswer.any_instance.should_receive(:update_attributes).with({ "question_id" => "1" })
        put :update, {:id => matching_answer.to_param, :matching_answer => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested matching_answer as @matching_answer" do
        matching_answer = MatchingAnswer.create! valid_attributes
        put :update, {:id => matching_answer.to_param, :matching_answer => valid_attributes}, valid_session
        assigns(:matching_answer).should eq(matching_answer)
      end

      it "redirects to the matching_answer" do
        matching_answer = MatchingAnswer.create! valid_attributes
        put :update, {:id => matching_answer.to_param, :matching_answer => valid_attributes}, valid_session
        response.should redirect_to(matching_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the matching_answer as @matching_answer" do
        matching_answer = MatchingAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MatchingAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => matching_answer.to_param, :matching_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:matching_answer).should eq(matching_answer)
      end

      it "re-renders the 'edit' template" do
        matching_answer = MatchingAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MatchingAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => matching_answer.to_param, :matching_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested matching_answer" do
      matching_answer = MatchingAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => matching_answer.to_param}, valid_session
      }.to change(MatchingAnswer, :count).by(-1)
    end

    it "redirects to the matching_answers list" do
      matching_answer = MatchingAnswer.create! valid_attributes
      delete :destroy, {:id => matching_answer.to_param}, valid_session
      response.should redirect_to(matching_answers_url)
    end
  end

end
