require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MultipleChoiceAnswersController do

  # This should return the minimal set of attributes required to create a valid
  # MultipleChoiceAnswer. As you add validations to MultipleChoiceAnswer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MultipleChoiceAnswersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all multiple_choice_answers as @multiple_choice_answers" do
      multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:multiple_choice_answers).should eq([multiple_choice_answer])
    end
  end

  describe "GET show" do
    it "assigns the requested multiple_choice_answer as @multiple_choice_answer" do
      multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
      get :show, {:id => multiple_choice_answer.to_param}, valid_session
      assigns(:multiple_choice_answer).should eq(multiple_choice_answer)
    end
  end

  describe "GET new" do
    it "assigns a new multiple_choice_answer as @multiple_choice_answer" do
      get :new, {}, valid_session
      assigns(:multiple_choice_answer).should be_a_new(MultipleChoiceAnswer)
    end
  end

  describe "GET edit" do
    it "assigns the requested multiple_choice_answer as @multiple_choice_answer" do
      multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
      get :edit, {:id => multiple_choice_answer.to_param}, valid_session
      assigns(:multiple_choice_answer).should eq(multiple_choice_answer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MultipleChoiceAnswer" do
        expect {
          post :create, {:multiple_choice_answer => valid_attributes}, valid_session
        }.to change(MultipleChoiceAnswer, :count).by(1)
      end

      it "assigns a newly created multiple_choice_answer as @multiple_choice_answer" do
        post :create, {:multiple_choice_answer => valid_attributes}, valid_session
        assigns(:multiple_choice_answer).should be_a(MultipleChoiceAnswer)
        assigns(:multiple_choice_answer).should be_persisted
      end

      it "redirects to the created multiple_choice_answer" do
        post :create, {:multiple_choice_answer => valid_attributes}, valid_session
        response.should redirect_to(MultipleChoiceAnswer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved multiple_choice_answer as @multiple_choice_answer" do
        # Trigger the behavior that occurs when invalid params are submitted
        MultipleChoiceAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:multiple_choice_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:multiple_choice_answer).should be_a_new(MultipleChoiceAnswer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MultipleChoiceAnswer.any_instance.stub(:save).and_return(false)
        post :create, {:multiple_choice_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested multiple_choice_answer" do
        multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
        # Assuming there are no other multiple_choice_answers in the database, this
        # specifies that the MultipleChoiceAnswer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MultipleChoiceAnswer.any_instance.should_receive(:update_attributes).with({ "question_id" => "1" })
        put :update, {:id => multiple_choice_answer.to_param, :multiple_choice_answer => { "question_id" => "1" }}, valid_session
      end

      it "assigns the requested multiple_choice_answer as @multiple_choice_answer" do
        multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
        put :update, {:id => multiple_choice_answer.to_param, :multiple_choice_answer => valid_attributes}, valid_session
        assigns(:multiple_choice_answer).should eq(multiple_choice_answer)
      end

      it "redirects to the multiple_choice_answer" do
        multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
        put :update, {:id => multiple_choice_answer.to_param, :multiple_choice_answer => valid_attributes}, valid_session
        response.should redirect_to(multiple_choice_answer)
      end
    end

    describe "with invalid params" do
      it "assigns the multiple_choice_answer as @multiple_choice_answer" do
        multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MultipleChoiceAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => multiple_choice_answer.to_param, :multiple_choice_answer => { "question_id" => "invalid value" }}, valid_session
        assigns(:multiple_choice_answer).should eq(multiple_choice_answer)
      end

      it "re-renders the 'edit' template" do
        multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MultipleChoiceAnswer.any_instance.stub(:save).and_return(false)
        put :update, {:id => multiple_choice_answer.to_param, :multiple_choice_answer => { "question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested multiple_choice_answer" do
      multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
      expect {
        delete :destroy, {:id => multiple_choice_answer.to_param}, valid_session
      }.to change(MultipleChoiceAnswer, :count).by(-1)
    end

    it "redirects to the multiple_choice_answers list" do
      multiple_choice_answer = MultipleChoiceAnswer.create! valid_attributes
      delete :destroy, {:id => multiple_choice_answer.to_param}, valid_session
      response.should redirect_to(multiple_choice_answers_url)
    end
  end

end
