require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QuestionDependencyPairsController do

  # This should return the minimal set of attributes required to create a valid
  # QuestionDependencyPair. As you add validations to QuestionDependencyPair, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "independent_question_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QuestionDependencyPairsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all question_dependency_pairs as @question_dependency_pairs" do
      question_dependency_pair = QuestionDependencyPair.create! valid_attributes
      get :index, {}, valid_session
      assigns(:question_dependency_pairs).should eq([question_dependency_pair])
    end
  end

  describe "GET show" do
    it "assigns the requested question_dependency_pair as @question_dependency_pair" do
      question_dependency_pair = QuestionDependencyPair.create! valid_attributes
      get :show, {:id => question_dependency_pair.to_param}, valid_session
      assigns(:question_dependency_pair).should eq(question_dependency_pair)
    end
  end

  describe "GET new" do
    it "assigns a new question_dependency_pair as @question_dependency_pair" do
      get :new, {}, valid_session
      assigns(:question_dependency_pair).should be_a_new(QuestionDependencyPair)
    end
  end

  describe "GET edit" do
    it "assigns the requested question_dependency_pair as @question_dependency_pair" do
      question_dependency_pair = QuestionDependencyPair.create! valid_attributes
      get :edit, {:id => question_dependency_pair.to_param}, valid_session
      assigns(:question_dependency_pair).should eq(question_dependency_pair)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QuestionDependencyPair" do
        expect {
          post :create, {:question_dependency_pair => valid_attributes}, valid_session
        }.to change(QuestionDependencyPair, :count).by(1)
      end

      it "assigns a newly created question_dependency_pair as @question_dependency_pair" do
        post :create, {:question_dependency_pair => valid_attributes}, valid_session
        assigns(:question_dependency_pair).should be_a(QuestionDependencyPair)
        assigns(:question_dependency_pair).should be_persisted
      end

      it "redirects to the created question_dependency_pair" do
        post :create, {:question_dependency_pair => valid_attributes}, valid_session
        response.should redirect_to(QuestionDependencyPair.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved question_dependency_pair as @question_dependency_pair" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionDependencyPair.any_instance.stub(:save).and_return(false)
        post :create, {:question_dependency_pair => { "independent_question_id" => "invalid value" }}, valid_session
        assigns(:question_dependency_pair).should be_a_new(QuestionDependencyPair)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionDependencyPair.any_instance.stub(:save).and_return(false)
        post :create, {:question_dependency_pair => { "independent_question_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested question_dependency_pair" do
        question_dependency_pair = QuestionDependencyPair.create! valid_attributes
        # Assuming there are no other question_dependency_pairs in the database, this
        # specifies that the QuestionDependencyPair created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QuestionDependencyPair.any_instance.should_receive(:update_attributes).with({ "independent_question_id" => "1" })
        put :update, {:id => question_dependency_pair.to_param, :question_dependency_pair => { "independent_question_id" => "1" }}, valid_session
      end

      it "assigns the requested question_dependency_pair as @question_dependency_pair" do
        question_dependency_pair = QuestionDependencyPair.create! valid_attributes
        put :update, {:id => question_dependency_pair.to_param, :question_dependency_pair => valid_attributes}, valid_session
        assigns(:question_dependency_pair).should eq(question_dependency_pair)
      end

      it "redirects to the question_dependency_pair" do
        question_dependency_pair = QuestionDependencyPair.create! valid_attributes
        put :update, {:id => question_dependency_pair.to_param, :question_dependency_pair => valid_attributes}, valid_session
        response.should redirect_to(question_dependency_pair)
      end
    end

    describe "with invalid params" do
      it "assigns the question_dependency_pair as @question_dependency_pair" do
        question_dependency_pair = QuestionDependencyPair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionDependencyPair.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_dependency_pair.to_param, :question_dependency_pair => { "independent_question_id" => "invalid value" }}, valid_session
        assigns(:question_dependency_pair).should eq(question_dependency_pair)
      end

      it "re-renders the 'edit' template" do
        question_dependency_pair = QuestionDependencyPair.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QuestionDependencyPair.any_instance.stub(:save).and_return(false)
        put :update, {:id => question_dependency_pair.to_param, :question_dependency_pair => { "independent_question_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested question_dependency_pair" do
      question_dependency_pair = QuestionDependencyPair.create! valid_attributes
      expect {
        delete :destroy, {:id => question_dependency_pair.to_param}, valid_session
      }.to change(QuestionDependencyPair, :count).by(-1)
    end

    it "redirects to the question_dependency_pairs list" do
      question_dependency_pair = QuestionDependencyPair.create! valid_attributes
      delete :destroy, {:id => question_dependency_pair.to_param}, valid_session
      response.should redirect_to(question_dependency_pairs_url)
    end
  end

end
